### PR TITLE
[debugger] Access invalid memory address using PointerValue Command. …

### LINKED ISSUE #15612: [sdb] Runtime crash when accessing invalid address under debugging
Unzip the following repro:

[reprosdb6.zip](https://github.com/mono/mono/files/3369391/reprosdb6.zip)

`./build.sh && mono debugger.exe`

Will result in a VM crash.

In this scenario, we're getting a `PointerValue` at an invalid address, and we're trying to dereference the pointer.

The debugger runtime should protect against a crash (~~could pointer evaluation be moved to managed?~~), and return an error to the debugger client access akin to an `AccessViolationException`.

### LINKED ISSUE #18191: Mono crashes on attemp to evaluate 'ref' returning method with debugger
## Steps to Reproduce
I've tried it with Rider 2019.3, but I guess it's also reproducible in other IDEs, because Rider does nothing special except the method invocation via SDB protocol

1. Create simple project with following code

```csharp
    internal class Program
    {
        private static int StaticF = 200;
        
        public static void Main(string[] args)
        { // set breakpoint here and evaluate 'RefReturn()'
        }
        
        public static ref int RefReturn()
        {
            return ref StaticF;
        }

    }
```

2.  Set a breakpoint on the start of Main()
3.  Start debugging and try to evaluate expression 'RefReturn()'

### Current Behavior
Mono crashes after a couple of seconds
`Process finished with exit code -1,073,741,819`

### Expected Behavior

The expression should be evaluated correctly

## On which platforms did you notice this

[ ] macOS (not tested)
[ ] Linux (not tested)
[ x] Windows

**Version Used**:
Mono JIT compiler version 6.6.0 (Visual Studio built mono)

### PR DESCRIPTION
**Pull request by UnityAlex**
…(#18537)

* Validate the address that came from IDE using PointerValue. The IDE can send an invalid address and it was crashing mono.

Fixes #18191
Fixes #15612

Co-authored-by: Aleksey Kliger (λgeek) <akliger@gmail.com>

Unity: Fixes case 1269030

### CODE REVIEW

File: mono/mini/debugger-agent.c [hunk 1]
```diff
@@ -11711,13 +11729,54 @@ string_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
 	return ERR_NONE;
 }
 
+static void 
+create_file_to_check_memory_address (void)
```
Comment (joncham) [inline mono/mini/debugger-agent.c:11734]: Seems like some things could be behind a `_MSC_VER` check but are not.

**Review by joncham — APPROVED** [review]

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/mono?pullRequest=1331) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/mono?pullRequest=1331) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/mono?pullRequest=1331) it.</sub>

File: mono/mini/debugger-agent.c (hunk 1 above)
Comment (UnityAlex) [reply mono/mini/debugger-agent.c:11734]: You're right this is only used in the `#ifndef _MSC_VER` check. I'll wrap this.
